# Generated by Django 4.2.9 on 2024-06-28 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=50)),
                ('school_contact1', models.CharField(max_length=10)),
                ('school_contact2', models.CharField(max_length=10)),
                ('school_contact3', models.CharField(blank=True, max_length=10, null=True)),
                ('school_box_number', models.CharField(max_length=10)),
                ('school_badge', models.ImageField(upload_to='school_badges/')),
            ],
        ),
    ]
