# Generated by Django 4.2.9 on 2024-07-01 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_schooldetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsubject',
            name='achievement',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='studentsubject',
            name='avg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentsubject',
            name='eighty_percent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentsubject',
            name='final_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentsubject',
            name='identifier',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='studentsubject',
            name='initials',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='studentsubject',
            name='twenty_percent',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
